name: 'close-and-comment'
description: 'Close issues with a comment'
inputs:
    exempt-users:
        description: 'Users to allow issues from'
        required: false
    close-comment:
        required: false
        default: 'No issues allowed.'
    github-token:
        description: 'The GitHub PAT to use to act'
        required: true
runs:
    using: 'node12'
    main: 'dist/index.js'
