on:
    issues:
        types: [opened]

jobs:
  comment-and-close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          exempt-users: varl,foo,bar
          github-token: ${{secrets.GH_TOKEN}}
